In [1]:
import numpy as np
import pandas as pd

import plotly.express as px

from sklearn.cluster import SpectralClustering
from sklearn.compose import ColumnTransformer
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    classification_report,
    confusion_matrix,
)
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, RobustScaler

# Clustering

In [2]:
# Config

INPUT_FILE = "../styles/fighter_career_stats.csv"
OUTPUT_FILE = "fighter_style_cluster.csv"

MIN_FIGHTS = 3
N_NEIGHBORS = 15
RANDOM_STATE = 100

K_VALUES = range(2, 16)


# Spectral clustering function

def run_spectral_clustering(
    input_file,
    K_CLUSTERS,
    MIN_FIGHTS,
    N_NEIGHBORS,
    RANDOM_STATE
):
    # 1. Load data

    df = pd.read_csv(input_file)

    df_model = df[df["total_fights"] >= MIN_FIGHTS].copy()

    # 2. Select clustering features

    exclude_cols = [
        "fighter",
        "total_fights",
        "total_fight_time"
    ]

    feature_cols = [
        col for col in df_model.columns
        if col not in exclude_cols
    ]

    feature_cols = [
        col for col in feature_cols
        if pd.api.types.is_numeric_dtype(df_model[col])
    ]

    # 3. Preprocess features

    X_raw = df_model[feature_cols].replace([np.inf, -np.inf], np.nan)

    preprocess = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", RobustScaler())
    ])

    X_scaled = preprocess.fit_transform(X_raw)

    # SpectralClustering requires n_neighbors < n_samples
    adjusted_n_neighbors = min(N_NEIGHBORS, len(df_model) - 1)

    # 4. Spectral clustering

    spectral = SpectralClustering(
        n_clusters=K_CLUSTERS,
        affinity="nearest_neighbors",
        n_neighbors=adjusted_n_neighbors,
        assign_labels="kmeans",
        random_state=RANDOM_STATE
    )

    df_model[f"style_k_{K_CLUSTERS}"] = spectral.fit_predict(X_scaled)

    # 5. Cluster counts and summary

    cluster_counts = (
        df_model[f"style_k_{K_CLUSTERS}"]
        .value_counts()
        .sort_index()
    )

    cluster_summary = (
        df_model
        .groupby(f"style_k_{K_CLUSTERS}")[feature_cols]
        .mean()
        .round(3)
    )

    cluster_summary_table = cluster_summary.T
    cluster_summary_table.index.name = "feature"

    cluster_summary_table.columns = [
        f"Cluster {col}" for col in cluster_summary_table.columns
    ]

    fighter_style_output = df_model[[
        "fighter",
        f"style_k_{K_CLUSTERS}"
    ]].copy()

    return fighter_style_output, cluster_counts, cluster_summary_table


# Run spectral clustering for k = 2 through 10

fighter_style_cluster = None
cluster_results = {}

for k in K_VALUES:
    print(f"\nRunning spectral clustering for k = {k}")

    fighter_k_styles, cluster_counts, cluster_summary_table = run_spectral_clustering(
        input_file=INPUT_FILE,
        K_CLUSTERS=k,
        MIN_FIGHTS=MIN_FIGHTS,
        N_NEIGHBORS=N_NEIGHBORS,
        RANDOM_STATE=RANDOM_STATE
    )

    print(f"\nCluster counts for k = {k}:")
    print(cluster_counts)

    cluster_results[k] = {
        "cluster_counts": cluster_counts,
        "cluster_summary_table": cluster_summary_table
    }

    if fighter_style_cluster is None:
        fighter_style_cluster = fighter_k_styles
    else:
        fighter_style_cluster = fighter_style_cluster.merge(
            fighter_k_styles,
            on="fighter",
            how="inner"
        )


# Save final fighter style cluster file

fighter_style_cluster = fighter_style_cluster.sort_values("fighter").reset_index(drop=True)

print("\nFinal shape:", fighter_style_cluster.shape)

fighter_style_cluster.to_csv(OUTPUT_FILE, index=False)

print(f"\nSaved: {OUTPUT_FILE}")

Running spectral clustering for k = 2

Cluster counts for k = 2:
style_k_2
0    1089
1     766
Name: count, dtype: int64

Running spectral clustering for k = 3

Cluster counts for k = 3:
style_k_3
0     387
1     419
2    1049
Name: count, dtype: int64

Running spectral clustering for k = 4

Cluster counts for k = 4:
style_k_4
0    1030
1     231
2     346
3     248
Name: count, dtype: int64

Running spectral clustering for k = 5

Cluster counts for k = 5:
style_k_5
0    235
1    202
2    258
3    331
4    829
Name: count, dtype: int64

Running spectral clustering for k = 6

Cluster counts for k = 6:
style_k_6
0    257
1    782
2    386
3    133
4    117
5    180
Name: count, dtype: int64

Running spectral clustering for k = 7

Cluster counts for k = 7:
style_k_7
0    288
1    105
2    222
3    308
4    646
5    155
6    131
Name: count, dtype: int64

Running spectral clustering for k = 8

Cluster counts for k = 8:
style_k_8
0    543
1    317
2    248
3    215
4     77
5     86
6    120
7    249
Name: count, dtype: int64

Running spectral clustering for k = 9

Cluster counts for k = 9:
style_k_9
0    536
1    223
2    160
3    105
4     69
5    159
6    310
7     79
8    214
Name: count, dtype: int64

Running spectral clustering for k = 10

Cluster counts for k = 10:
style_k_10
0    269
1    404
2     67
3    176
4    214
5    324
6    148
7     90
8     97
9     66
Name: count, dtype: int64

Running spectral clustering for k = 11

Cluster counts for k = 11:
style_k_11
0      66
1     135
2     206
3      98
4     245
5      72
6     310
7     174
8      93
9      65
10    391
Name: count, dtype: int64

Running spectral clustering for k = 12

Cluster counts for k = 12:
style_k_12
0      73
1     222
2     340
3     294
4      91
5     137
6     213
7      69
8      58
9     221
10     60
11     77
Name: count, dtype: int64

Running spectral clustering for k = 13

Cluster counts for k = 13:
style_k_13
0     123
1      53
2     269
3      69
4      97
5     301
6      58
7     226
8     197
9      51
10    153
11    186
12     72
Name: count, dtype: int64

Running spectral clustering for k = 14

Cluster counts for k = 14:
style_k_14
0      59
1     359
2      44
3     155
4     193
5      83
6      73
7      50
8     237
9     202
10     73
11    169
12     54
13    104
Name: count, dtype: int64

Running spectral clustering for k = 15

Cluster counts for k = 15:
style_k_15
0      85
1     359
2     155
3     172
4      43
5     196
6      48
7      60
8      59
9      57
10    170
11    164
12     49
13    174
14     64
Name: count, dtype: int64

Final shape: (1855, 15)

Saved: fighter_style_cluster.csv

# PreProcess before RF

In [3]:
import pandas as pd
import numpy as np


# ------------------------------------------------------------
# Config
# ------------------------------------------------------------

FIGHT_FILE = "../styles/clean_total_fight_data.csv"
STYLE_FILE = "fighter_style_cluster.csv"

OUTPUT_FILE = "style_matchup_rf_data_all_k.csv"


# ------------------------------------------------------------
# 1. Load data
# ------------------------------------------------------------

fights = pd.read_csv(FIGHT_FILE)
fighter_styles = pd.read_csv(STYLE_FILE)

# Make sure names are clean strings
for col in ["winner", "R_fighter", "B_fighter"]:
    fights[col] = fights[col].astype(str).str.strip()

fighter_styles["fighter"] = fighter_styles["fighter"].astype(str).str.strip()


# ------------------------------------------------------------
# 2. Validate style columns
# ------------------------------------------------------------

style_cols = [f"style_k_{k}" for k in K_VALUES]

missing_style_cols = [
    col for col in style_cols
    if col not in fighter_styles.columns
]

if missing_style_cols:
    raise ValueError(f"Missing style columns in {STYLE_FILE}: {missing_style_cols}")


# ------------------------------------------------------------
# 3. Merge k=2...10 styles into fight-level data
# ------------------------------------------------------------

r_styles = fighter_styles[["fighter"] + style_cols].rename(columns={
    "fighter": "R_fighter",
    **{f"style_k_{k}": f"R_style_k_{k}" for k in K_VALUES}
})

b_styles = fighter_styles[["fighter"] + style_cols].rename(columns={
    "fighter": "B_fighter",
    **{f"style_k_{k}": f"B_style_k_{k}" for k in K_VALUES}
})

style_matchups = (
    fights[["winner", "R_fighter", "B_fighter"]]
    .merge(r_styles, on="R_fighter", how="left")
    .merge(b_styles, on="B_fighter", how="left")
)

print("\nRows before dropping missing styles:", len(style_matchups))

# Drop fights where either fighter is missing any style assignment
required_style_cols = (
    [f"R_style_k_{k}" for k in K_VALUES] +
    [f"B_style_k_{k}" for k in K_VALUES]
)

style_matchups = style_matchups.dropna(subset=required_style_cols).copy()

print("Rows after dropping missing styles:", len(style_matchups))


# ------------------------------------------------------------
# 4. Convert winner name into R/B target
# ------------------------------------------------------------

def get_winner_side(row):
    winner = str(row["winner"]).strip()
    r_fighter = str(row["R_fighter"]).strip()
    b_fighter = str(row["B_fighter"]).strip()

    if winner == r_fighter:
        return "R"
    elif winner == b_fighter:
        return "B"
    elif winner.lower() in ["r", "red", "r_fighter"]:
        return "R"
    elif winner.lower() in ["b", "blue", "b_fighter"]:
        return "B"
    else:
        return np.nan


style_matchups["winner_side"] = style_matchups.apply(get_winner_side, axis=1)

print("\nRows before dropping unknown winner:", len(style_matchups))

style_matchups = style_matchups.dropna(subset=["winner_side"]).copy()

print("Rows after dropping unknown winner:", len(style_matchups))


# ------------------------------------------------------------
# 5. Randomly assign neutral fighter_1 / fighter_2 sides
# ------------------------------------------------------------

rng = np.random.default_rng(RANDOM_STATE)

# True = keep R as fighter_1, B as fighter_2
# False = swap B into fighter_1, R into fighter_2
style_matchups["keep_original_order"] = rng.choice(
    [True, False],
    size=len(style_matchups),
    replace=True
)

style_matchups["fighter_1"] = np.where(
    style_matchups["keep_original_order"],
    style_matchups["R_fighter"],
    style_matchups["B_fighter"]
)

style_matchups["fighter_2"] = np.where(
    style_matchups["keep_original_order"],
    style_matchups["B_fighter"],
    style_matchups["R_fighter"]
)

# Target: did fighter_1 win?
style_matchups["fighter_1_won"] = np.where(
    (
        (style_matchups["keep_original_order"] & (style_matchups["winner_side"] == "R")) |
        (~style_matchups["keep_original_order"] & (style_matchups["winner_side"] == "B"))
    ),
    1,
    0
)


# ------------------------------------------------------------
# 6. Add fighter_1 / fighter_2 style columns for every k
# ------------------------------------------------------------

for k in K_VALUES:
    r_col = f"R_style_k_{k}"
    b_col = f"B_style_k_{k}"

    f1_col = f"fighter_1_style_k_{k}"
    f2_col = f"fighter_2_style_k_{k}"

    style_matchups[f1_col] = np.where(
        style_matchups["keep_original_order"],
        style_matchups[r_col],
        style_matchups[b_col]
    )

    style_matchups[f2_col] = np.where(
        style_matchups["keep_original_order"],
        style_matchups[b_col],
        style_matchups[r_col]
    )

    # Keep style IDs categorical
    style_matchups[f1_col] = style_matchups[f1_col].astype(int).astype(str)
    style_matchups[f2_col] = style_matchups[f2_col].astype(int).astype(str)


# ------------------------------------------------------------
# 7. Final RF dataset
# ------------------------------------------------------------

final_cols = [
    "fighter_1",
    "fighter_2",
    "fighter_1_won"
]

for k in K_VALUES:
    final_cols.extend([
        f"fighter_1_style_k_{k}",
        f"fighter_2_style_k_{k}"
    ])

rf_data_final = style_matchups[final_cols].copy()

# Shuffle final rows
rf_data_final = (
    rf_data_final
    .sample(frac=1, random_state=RANDOM_STATE)
    .reset_index(drop=True)
)


print("\nTarget distribution:")
print(rf_data_final["fighter_1_won"].value_counts())

Rows before dropping missing styles: 8693
Rows after dropping missing styles: 7531

Rows before dropping unknown winner: 7531
Rows after dropping unknown winner: 7392

Target distribution:
fighter_1_won
1    3718
0    3674
Name: count, dtype: int64

# Random Forest

In [4]:
# ------------------------------------------------------------
# Random Forest comparison across k = 2...10
# ------------------------------------------------------------

# Random Forest function

def run_style_rf_for_k(
    rf_data_final,
    k,
    random_state=100,
    test_size=0.20,
    cv=5,
    print_results=True
):
    fighter_1_col = f"fighter_1_style_k_{k}"
    fighter_2_col = f"fighter_2_style_k_{k}"
    target_col = "fighter_1_won"

    required_cols = [fighter_1_col, fighter_2_col, target_col]

    missing_cols = [
        col for col in required_cols
        if col not in rf_data_final.columns
    ]

    if missing_cols:
        raise ValueError(f"Missing required columns for k={k}: {missing_cols}")

    # --------------------------------------------------------
    # Remove same-style matchups for this specific k
    # --------------------------------------------------------

    data_k = rf_data_final[required_cols].copy()

    data_k[fighter_1_col] = data_k[fighter_1_col].astype(str)
    data_k[fighter_2_col] = data_k[fighter_2_col].astype(str)

    rows_before = len(data_k)

    data_k = data_k[data_k[fighter_1_col] != data_k[fighter_2_col]].copy()

    rows_after = len(data_k)
    rows_removed = rows_before - rows_after

    if data_k[target_col].nunique() < 2:
        raise ValueError(f"Only one target class remains after filtering same-style matchups for k={k}.")

    # --------------------------------------------------------
    # Predictors and target
    # --------------------------------------------------------

    X = data_k[[fighter_1_col, fighter_2_col]].copy()
    y = data_k[target_col].copy()

    # --------------------------------------------------------
    # Train/test split
    # --------------------------------------------------------

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=test_size,
        random_state=random_state,
        stratify=y
    )

    # --------------------------------------------------------
    # One-hot encode style IDs
    # --------------------------------------------------------

    try:
        encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
    except TypeError:
        encoder = OneHotEncoder(handle_unknown="ignore", sparse=False)

    preprocess_rf = ColumnTransformer(
        transformers=[
            ("style_ohe", encoder, [fighter_1_col, fighter_2_col])
        ],
        remainder="drop"
    )

    rf_model = RandomForestClassifier(
        n_estimators=500,
        max_depth=None,
        min_samples_leaf=10,
        class_weight="balanced",
        random_state=random_state,
        n_jobs=-1
    )

    rf_pipeline = Pipeline(steps=[
        ("preprocess", preprocess_rf),
        ("model", rf_model)
    ])

    # --------------------------------------------------------
    # Fit and evaluate train/test
    # --------------------------------------------------------

    rf_pipeline.fit(X_train, y_train)

    y_pred = rf_pipeline.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    balanced_accuracy = balanced_accuracy_score(y_test, y_pred)

    cm = confusion_matrix(y_test, y_pred, labels=[1, 0])

    # --------------------------------------------------------
    # Cross-validation
    # --------------------------------------------------------

    cv_scores = cross_val_score(
        rf_pipeline,
        X,
        y,
        cv=cv,
        scoring="balanced_accuracy",
        n_jobs=-1
    )

    result = {
        "k": k,
        "rows_before_filter": rows_before,
        "rows_after_filter": rows_after,
        "same_style_rows_removed": rows_removed,
        "target_1_rate": y.mean(),
        "test_accuracy": accuracy,
        "test_balanced_accuracy": balanced_accuracy,
        "cv_mean_balanced_accuracy": cv_scores.mean(),
        "cv_std_balanced_accuracy": cv_scores.std(),
        "cv_scores": cv_scores,
        "confusion_matrix": cm
    }

    if print_results:
        print("\n" + "-" * 60)
        print(f"k = {k}")
        print("-" * 60)

        print("Rows before same-style filter:", rows_before)
        print("Rows after same-style filter:", rows_after)
        print("Same-style rows removed:", rows_removed)

        print("\nTarget distribution:")
        print(y.value_counts(normalize=True).round(3))
        print(y.value_counts())

        print("\nTest accuracy:", round(accuracy, 3))
        print("Test balanced accuracy:", round(balanced_accuracy, 3))

        print("\nConfusion matrix:")
        print(cm)

        print(f"\n{CV}-fold CV balanced accuracy:")
        print(cv_scores.round(3))
        print("Mean:", round(cv_scores.mean(), 3))
        print("Std:", round(cv_scores.std(), 3))

    return result


# ------------------------------------------------------------
# Run RF for each k
# ------------------------------------------------------------

CV = 15

rf_results = []

for k in K_VALUES:
    result_k = run_style_rf_for_k(
        rf_data_final=rf_data_final,
        k=k,
        random_state=RANDOM_STATE,
        test_size=0.20,
        cv=CV,
        print_results=True
    )

    rf_results.append(result_k)


# ------------------------------------------------------------
# Compare all k values
# ------------------------------------------------------------

rf_results_table = pd.DataFrame([
    {
        "k": r["k"],
        "rows_before_filter": r["rows_before_filter"],
        "rows_after_filter": r["rows_after_filter"],
        "same_style_rows_removed": r["same_style_rows_removed"],
        "target_1_rate": round(r["target_1_rate"], 3),
        "test_accuracy": round(r["test_accuracy"], 3),
        "test_balanced_accuracy": round(r["test_balanced_accuracy"], 3),
        "cv_mean_balanced_accuracy": round(r["cv_mean_balanced_accuracy"], 3),
        "cv_std_balanced_accuracy": round(r["cv_std_balanced_accuracy"], 3)
    }
    for r in rf_results
])

rf_results_table = (
    rf_results_table
    .sort_values("cv_mean_balanced_accuracy", ascending=False)
    .reset_index(drop=True)
)

print("\n" + "=" * 80)
print("Random Forest performance by k")
print("=" * 80)

display(rf_results_table)

best_k = rf_results_table.loc[0, "k"]
best_cv_score = rf_results_table.loc[0, "cv_mean_balanced_accuracy"]

print(f"\nBest k by CV balanced accuracy: {best_k}")
print(f"Best CV balanced accuracy: {best_cv_score}")

------------------------------------------------------------
k = 2
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 2782
Same-style rows removed: 4610

Target distribution:
fighter_1_won
1    0.511
0    0.489
Name: proportion, dtype: float64
fighter_1_won
1    1421
0    1361
Name: count, dtype: int64

Test accuracy: 0.524
Test balanced accuracy: 0.525

Confusion matrix:
[[141 144]
 [121 151]]

15-fold CV balanced accuracy:
[0.564 0.532 0.469 0.41  0.458 0.537 0.538 0.518 0.535 0.534 0.507 0.552
 0.486 0.526 0.481]
Mean: 0.51
Std: 0.04

------------------------------------------------------------
k = 3
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 3832
Same-style rows removed: 3560

Target distribution:
fighter_1_won
1    0.503
0    0.497
Name: proportion, dtype: float64
fighter_1_won
1    1926
0    1906
Name: count, dtype: int64

Test accuracy: 0.551
Test balanced accuracy: 0.551

Confusion matrix:
[[224 162]
 [182 199]]

15-fold CV balanced accuracy:
[0.535 0.539 0.578 0.605 0.547 0.539 0.547 0.533 0.549 0.565 0.545 0.576
 0.541 0.56  0.51 ]
Mean: 0.551
Std: 0.022

------------------------------------------------------------
k = 4
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 4010
Same-style rows removed: 3382

Target distribution:
fighter_1_won
1    0.507
0    0.493
Name: proportion, dtype: float64
fighter_1_won
1    2035
0    1975
Name: count, dtype: int64

Test accuracy: 0.612
Test balanced accuracy: 0.612

Confusion matrix:
[[244 163]
 [148 247]]

15-fold CV balanced accuracy:
[0.615 0.586 0.619 0.605 0.604 0.596 0.641 0.566 0.569 0.636 0.584 0.565
 0.539 0.625 0.626]
Mean: 0.598
Std: 0.029

------------------------------------------------------------
k = 5
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 4604
Same-style rows removed: 2788

Target distribution:
fighter_1_won
1    0.505
0    0.495
Name: proportion, dtype: float64
fighter_1_won
1    2326
0    2278
Name: count, dtype: int64

Test accuracy: 0.584
Test balanced accuracy: 0.583

Confusion matrix:
[[307 158]
 [225 231]]

15-fold CV balanced accuracy:
[0.612 0.596 0.619 0.58  0.596 0.593 0.651 0.577 0.589 0.615 0.593 0.576
 0.586 0.606 0.618]
Mean: 0.601
Std: 0.019

------------------------------------------------------------
k = 6
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 4683
Same-style rows removed: 2709

Target distribution:
fighter_1_won
1    0.505
0    0.495
Name: proportion, dtype: float64
fighter_1_won
1    2367
0    2316
Name: count, dtype: int64

Test accuracy: 0.588
Test balanced accuracy: 0.588

Confusion matrix:
[[283 191]
 [195 268]]

15-fold CV balanced accuracy:
[0.571 0.629 0.575 0.57  0.612 0.571 0.64  0.609 0.596 0.605 0.583 0.593
 0.561 0.561 0.632]
Mean: 0.594
Std: 0.026

------------------------------------------------------------
k = 7
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 5342
Same-style rows removed: 2050

Target distribution:
fighter_1_won
1    0.503
0    0.497
Name: proportion, dtype: float64
fighter_1_won
1    2685
0    2657
Name: count, dtype: int64

Test accuracy: 0.606
Test balanced accuracy: 0.606

Confusion matrix:
[[362 175]
 [246 286]]

15-fold CV balanced accuracy:
[0.58  0.602 0.582 0.601 0.637 0.601 0.646 0.615 0.601 0.632 0.576 0.573
 0.593 0.575 0.621]
Mean: 0.602
Std: 0.023

------------------------------------------------------------
k = 8
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 5610
Same-style rows removed: 1782

Target distribution:
fighter_1_won
1    0.501
0    0.499
Name: proportion, dtype: float64
fighter_1_won
1    2811
0    2799
Name: count, dtype: int64

Test accuracy: 0.59
Test balanced accuracy: 0.59

Confusion matrix:
[[337 225]
 [235 325]]

15-fold CV balanced accuracy:
[0.599 0.625 0.562 0.623 0.61  0.618 0.655 0.602 0.599 0.58  0.596 0.596
 0.58  0.586 0.604]
Mean: 0.602
Std: 0.022

------------------------------------------------------------
k = 9
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 5752
Same-style rows removed: 1640

Target distribution:
fighter_1_won
1    0.502
0    0.498
Name: proportion, dtype: float64
fighter_1_won
1    2889
0    2863
Name: count, dtype: int64

Test accuracy: 0.615
Test balanced accuracy: 0.615

Confusion matrix:
[[378 200]
 [243 330]]

15-fold CV balanced accuracy:
[0.601 0.596 0.578 0.641 0.609 0.622 0.641 0.579 0.6   0.6   0.58  0.59
 0.59  0.624 0.606]
Mean: 0.604
Std: 0.02

------------------------------------------------------------
k = 10
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 5992
Same-style rows removed: 1400

Target distribution:
fighter_1_won
1    0.501
0    0.499
Name: proportion, dtype: float64
fighter_1_won
1    3001
0    2991
Name: count, dtype: int64

Test accuracy: 0.614
Test balanced accuracy: 0.614

Confusion matrix:
[[383 218]
 [245 353]]

15-fold CV balanced accuracy:
[0.585 0.628 0.578 0.6   0.635 0.622 0.655 0.609 0.579 0.599 0.586 0.576
 0.581 0.634 0.634]
Mean: 0.607
Std: 0.025

------------------------------------------------------------
k = 11
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 6057
Same-style rows removed: 1335

Target distribution:
fighter_1_won
1    0.503
0    0.497
Name: proportion, dtype: float64
fighter_1_won
1    3046
0    3011
Name: count, dtype: int64

Test accuracy: 0.57
Test balanced accuracy: 0.57

Confusion matrix:
[[346 264]
 [257 345]]

15-fold CV balanced accuracy:
[0.581 0.606 0.592 0.626 0.599 0.594 0.659 0.577 0.597 0.559 0.562 0.586
 0.571 0.622 0.618]
Mean: 0.597
Std: 0.026

------------------------------------------------------------
k = 12
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 6147
Same-style rows removed: 1245

Target distribution:
fighter_1_won
0    0.5
1    0.5
Name: proportion, dtype: float64
fighter_1_won
0    3076
1    3071
Name: count, dtype: int64

Test accuracy: 0.613
Test balanced accuracy: 0.613

Confusion matrix:
[[405 209]
 [267 349]]

15-fold CV balanced accuracy:
[0.583 0.629 0.607 0.639 0.617 0.651 0.661 0.637 0.612 0.593 0.559 0.583
 0.611 0.619 0.641]
Mean: 0.616
Std: 0.027

------------------------------------------------------------
k = 13
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 6318
Same-style rows removed: 1074

Target distribution:
fighter_1_won
0    0.5
1    0.5
Name: proportion, dtype: float64
fighter_1_won
0    3162
1    3156
Name: count, dtype: int64

Test accuracy: 0.619
Test balanced accuracy: 0.619

Confusion matrix:
[[419 212]
 [270 363]]

15-fold CV balanced accuracy:
[0.583 0.592 0.602 0.625 0.603 0.603 0.634 0.603 0.582 0.582 0.573 0.554
 0.603 0.584 0.625]
Mean: 0.597
Std: 0.021

------------------------------------------------------------
k = 14
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 6305
Same-style rows removed: 1087

Target distribution:
fighter_1_won
1    0.504
0    0.496
Name: proportion, dtype: float64
fighter_1_won
1    3177
0    3128
Name: count, dtype: int64

Test accuracy: 0.59
Test balanced accuracy: 0.59

Confusion matrix:
[[386 249]
 [268 358]]

15-fold CV balanced accuracy:
[0.58  0.601 0.58  0.632 0.62  0.588 0.638 0.562 0.586 0.574 0.571 0.571
 0.617 0.645 0.609]
Mean: 0.598
Std: 0.026

------------------------------------------------------------
k = 15
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 6387
Same-style rows removed: 1005

Target distribution:
fighter_1_won
1    0.505
0    0.495
Name: proportion, dtype: float64
fighter_1_won
1    3228
0    3159
Name: count, dtype: int64

Test accuracy: 0.588
Test balanced accuracy: 0.589

Confusion matrix:
[[358 288]
 [238 394]]

15-fold CV balanced accuracy:
[0.565 0.601 0.575 0.61  0.63  0.601 0.615 0.599 0.589 0.571 0.577 0.574
 0.586 0.633 0.619]
Mean: 0.596
Std: 0.021

================================================================================
Random Forest performance by k
================================================================================

,k,rows_before_filter,rows_after_filter,same_style_rows_removed,target_1_rate,test_accuracy,test_balanced_accuracy,cv_mean_balanced_accuracy,cv_std_balanced_accuracy
0,12,7392,6147,1245,0.500,0.613,0.613,0.616,0.027
1,10,7392,5992,1400,0.501,0.614,0.614,0.607,0.025
2,9,7392,5752,1640,0.502,0.615,0.615,0.604,0.020
3,8,7392,5610,1782,0.501,0.590,0.590,0.602,0.022
4,7,7392,5342,2050,0.503,0.606,0.606,0.602,0.023
5,5,7392,4604,2788,0.505,0.584,0.583,0.601,0.019
6,14,7392,6305,1087,0.504,0.590,0.590,0.598,0.026
7,4,7392,4010,3382,0.507,0.612,0.612,0.598,0.029
8,13,7392,6318,1074,0.500,0.619,0.619,0.597,0.021
9,11,7392,6057,1335,0.503,0.570,0.570,0.597,0.026
10,15,7392,6387,1005,0.505,0.588,0.589,0.596,0.021
11,6,7392,4683,2709,0.505,0.588,0.588,0.594,0.026
12,3,7392,3832,3560,0.503,0.551,0.551,0.551,0.022
13,2,7392,2782,4610,0.511,0.524,0.525,0.510,0.040

Best k by CV balanced accuracy: 12
Best CV balanced accuracy: 0.616

# Weighted Clustering

In [ ]:
import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import RobustScaler
from sklearn.pipeline import Pipeline
from sklearn.cluster import SpectralClustering


# ------------------------------------------------------------
# Config
# ------------------------------------------------------------

INPUT_FILE = "../styles/fighter_career_stats.csv"
OUTPUT_FILE = "weighted_fighter_style_cluster.csv"

MIN_FIGHTS = 3
N_NEIGHBORS = 15
RANDOM_STATE = 100

K_VALUES = range(2, 16)


# ------------------------------------------------------------
# Feature weighting
# ------------------------------------------------------------

HIGH_WEIGHT = 2.0
MID_WEIGHT = 1.0
LOW_WEIGHT = 0.5


def get_feature_weight(feature_name):
    """
    Assigns feature weights after scaling.
    """

    # Highest weight features
    if (
        feature_name == "fight_quickness"
        or feature_name.startswith("win_")
        or feature_name.endswith("_att_per_min")
        or feature_name in ["CTRL_pct", "KD_per_min", "SUB_ATT_per_min"]
    ):
        return HIGH_WEIGHT

    # Lowest weight features
    elif (
        feature_name.startswith("loss_")
        or feature_name.endswith("_absorbed_per_min")
        or feature_name.endswith("_opp_att_per_min")
    ):
        return LOW_WEIGHT

    # Middle weight features
    elif (
        feature_name.endswith("_acc")
        or feature_name == "REV_per_min"
        or feature_name.endswith("_land_per_min")
        or feature_name.endswith("_def")
    ):
        return MID_WEIGHT

    # Default to middle weight if a numeric feature is not explicitly categorized
    else:
        return MID_WEIGHT


# ------------------------------------------------------------
# Spectral clustering function
# ------------------------------------------------------------

def run_spectral_clustering(
    input_file,
    K_CLUSTERS,
    MIN_FIGHTS,
    N_NEIGHBORS,
    RANDOM_STATE
):
    # --------------------------------------------------------
    # 1. Load data
    # --------------------------------------------------------

    df = pd.read_csv(input_file)

    df_model = df[df["total_fights"] >= MIN_FIGHTS].copy()

    # --------------------------------------------------------
    # 2. Select clustering features
    # --------------------------------------------------------

    exclude_cols = [
        "fighter",
        "total_fights",
        "total_fight_time"
    ]

    feature_cols = [
        col for col in df_model.columns
        if col not in exclude_cols
    ]

    feature_cols = [
        col for col in feature_cols
        if pd.api.types.is_numeric_dtype(df_model[col])
    ]

    # --------------------------------------------------------
    # 3. Preprocess features
    # --------------------------------------------------------

    X_raw = df_model[feature_cols].replace([np.inf, -np.inf], np.nan)

    preprocess = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", RobustScaler())
    ])

    X_scaled = preprocess.fit_transform(X_raw)

    # --------------------------------------------------------
    # 4. Apply feature weights after scaling
    # --------------------------------------------------------

    feature_weights = np.array([
        get_feature_weight(col)
        for col in feature_cols
    ])

    X_weighted = X_scaled * feature_weights

    weights_table = pd.DataFrame({
        "feature": feature_cols,
        "weight": feature_weights
    })

    # SpectralClustering requires n_neighbors < n_samples
    adjusted_n_neighbors = min(N_NEIGHBORS, len(df_model) - 1)

    # --------------------------------------------------------
    # 5. Spectral clustering
    # --------------------------------------------------------

    spectral = SpectralClustering(
        n_clusters=K_CLUSTERS,
        affinity="nearest_neighbors",
        n_neighbors=adjusted_n_neighbors,
        assign_labels="kmeans",
        random_state=RANDOM_STATE
    )

    df_model[f"style_k_{K_CLUSTERS}"] = spectral.fit_predict(X_weighted)

    # --------------------------------------------------------
    # 6. Cluster counts and summary
    # --------------------------------------------------------

    cluster_counts = (
        df_model[f"style_k_{K_CLUSTERS}"]
        .value_counts()
        .sort_index()
    )

    cluster_summary = (
        df_model
        .groupby(f"style_k_{K_CLUSTERS}")[feature_cols]
        .mean()
        .round(3)
    )

    cluster_summary_table = cluster_summary.T
    cluster_summary_table.index.name = "feature"

    cluster_summary_table.columns = [
        f"Cluster {col}" for col in cluster_summary_table.columns
    ]

    fighter_style_output = df_model[[
        "fighter",
        f"style_k_{K_CLUSTERS}"
    ]].copy()

    return fighter_style_output, cluster_counts, cluster_summary_table, weights_table


# ------------------------------------------------------------
# Run spectral clustering for k = 2 through 15
# ------------------------------------------------------------

fighter_style_cluster = None
cluster_results = {}
weights_table = None

for k in K_VALUES:
    print(f"\nRunning weighted spectral clustering for k = {k}")

    fighter_k_styles, cluster_counts, cluster_summary_table, weights_table = run_spectral_clustering(
        input_file=INPUT_FILE,
        K_CLUSTERS=k,
        MIN_FIGHTS=MIN_FIGHTS,
        N_NEIGHBORS=N_NEIGHBORS,
        RANDOM_STATE=RANDOM_STATE
    )

    print(f"\nCluster counts for k = {k}:")
    print(cluster_counts)

    cluster_results[k] = {
        "cluster_counts": cluster_counts,
        "cluster_summary_table": cluster_summary_table
    }

    if fighter_style_cluster is None:
        fighter_style_cluster = fighter_k_styles
    else:
        fighter_style_cluster = fighter_style_cluster.merge(
            fighter_k_styles,
            on="fighter",
            how="inner"
        )


# ------------------------------------------------------------
# Save final fighter style cluster file
# ------------------------------------------------------------

fighter_style_cluster = (
    fighter_style_cluster
    .sort_values("fighter")
    .reset_index(drop=True)
)

print("\nFinal shape:", fighter_style_cluster.shape)

fighter_style_cluster.to_csv(OUTPUT_FILE, index=False)

print(f"\nSaved: {OUTPUT_FILE}")

Running weighted spectral clustering for k = 2

Cluster counts for k = 2:
style_k_2
0    1101
1     754
Name: count, dtype: int64

Running weighted spectral clustering for k = 3

Cluster counts for k = 3:
style_k_3
0     398
1     407
2    1050
Name: count, dtype: int64

Running weighted spectral clustering for k = 4

Cluster counts for k = 4:
style_k_4
0    258
1    394
2    939
3    264
Name: count, dtype: int64

Running weighted spectral clustering for k = 5

Cluster counts for k = 5:
style_k_5
0    808
1    255
2    348
3    202
4    242
Name: count, dtype: int64

Running weighted spectral clustering for k = 6

Cluster counts for k = 6:
style_k_6
0     95
1    426
2    671
3    148
4    128
5    387
Name: count, dtype: int64

Running weighted spectral clustering for k = 7

Cluster counts for k = 7:
style_k_7
0    107
1    211
2    248
3    136
4    674
5    121
6    358
Name: count, dtype: int64

Running weighted spectral clustering for k = 8

Cluster counts for k = 8:
style_k_8
0    414
1    412
2    206
3    231
4    264
5    122
6     94
7    112
Name: count, dtype: int64

Running weighted spectral clustering for k = 9

Cluster counts for k = 9:
style_k_9
0    166
1    410
2    219
3    112
4    101
5     85
6    307
7    357
8     98
Name: count, dtype: int64

Running weighted spectral clustering for k = 10

Cluster counts for k = 10:
style_k_10
0    235
1     95
2    183
3     92
4     86
5    161
6    101
7    319
8    162
9    421
Name: count, dtype: int64

Running weighted spectral clustering for k = 11

Cluster counts for k = 11:
style_k_11
0     179
1     220
2     403
3      71
4     101
5     207
6     154
7     119
8      77
9      84
10    240
Name: count, dtype: int64

Running weighted spectral clustering for k = 12

Cluster counts for k = 12:
style_k_12
0      84
1     194
2     143
3     358
4      68
5      70
6     221
7      77
8     158
9      82
10    155
11    245
Name: count, dtype: int64

Running weighted spectral clustering for k = 13

Cluster counts for k = 13:
style_k_13
0      65
1     226
2      80
3     158
4     209
5     210
6      81
7      79
8      54
9      69
10    346
11    140
12    138
Name: count, dtype: int64

Running weighted spectral clustering for k = 14

Cluster counts for k = 14:
style_k_14
0      65
1     209
2     185
3      60
4      77
5     137
6     124
7     156
8     180
9      68
10     45
11     78
12    318
13    153
Name: count, dtype: int64

Running weighted spectral clustering for k = 15

Cluster counts for k = 15:
style_k_15
0     113
1     337
2      62
3     125
4     151
5     181
6      68
7      43
8     148
9      50
10    216
11    137
12     77
13     79
14     68
Name: count, dtype: int64

Final shape: (1855, 15)

Saved: fighter_style_cluster_weighted.csv

# RF Weighted PreProcess

In [8]:
# ------------------------------------------------------------
# Config
# ------------------------------------------------------------

FIGHT_FILE = "../styles/clean_total_fight_data.csv"
STYLE_FILE = "weighted_fighter_style_cluster.csv"

OUTPUT_FILE = "weighted_style_matchup_rf_data_all_k.csv"


# ------------------------------------------------------------
# 1. Load data
# ------------------------------------------------------------

fights = pd.read_csv(FIGHT_FILE)
fighter_styles = pd.read_csv(STYLE_FILE)

# Make sure names are clean strings
for col in ["winner", "R_fighter", "B_fighter"]:
    fights[col] = fights[col].astype(str).str.strip()

fighter_styles["fighter"] = fighter_styles["fighter"].astype(str).str.strip()


# ------------------------------------------------------------
# 2. Validate style columns
# ------------------------------------------------------------

style_cols = [f"style_k_{k}" for k in K_VALUES]

missing_style_cols = [
    col for col in style_cols
    if col not in fighter_styles.columns
]

if missing_style_cols:
    raise ValueError(f"Missing style columns in {STYLE_FILE}: {missing_style_cols}")


# ------------------------------------------------------------
# 3. Merge k=2...10 styles into fight-level data
# ------------------------------------------------------------

r_styles = fighter_styles[["fighter"] + style_cols].rename(columns={
    "fighter": "R_fighter",
    **{f"style_k_{k}": f"R_style_k_{k}" for k in K_VALUES}
})

b_styles = fighter_styles[["fighter"] + style_cols].rename(columns={
    "fighter": "B_fighter",
    **{f"style_k_{k}": f"B_style_k_{k}" for k in K_VALUES}
})

style_matchups = (
    fights[["winner", "R_fighter", "B_fighter"]]
    .merge(r_styles, on="R_fighter", how="left")
    .merge(b_styles, on="B_fighter", how="left")
)

print("\nRows before dropping missing styles:", len(style_matchups))

# Drop fights where either fighter is missing any style assignment
required_style_cols = (
    [f"R_style_k_{k}" for k in K_VALUES] +
    [f"B_style_k_{k}" for k in K_VALUES]
)

style_matchups = style_matchups.dropna(subset=required_style_cols).copy()

print("Rows after dropping missing styles:", len(style_matchups))


# ------------------------------------------------------------
# 4. Convert winner name into R/B target
# ------------------------------------------------------------

def get_winner_side(row):
    winner = str(row["winner"]).strip()
    r_fighter = str(row["R_fighter"]).strip()
    b_fighter = str(row["B_fighter"]).strip()

    if winner == r_fighter:
        return "R"
    elif winner == b_fighter:
        return "B"
    elif winner.lower() in ["r", "red", "r_fighter"]:
        return "R"
    elif winner.lower() in ["b", "blue", "b_fighter"]:
        return "B"
    else:
        return np.nan


style_matchups["winner_side"] = style_matchups.apply(get_winner_side, axis=1)

print("\nRows before dropping unknown winner:", len(style_matchups))

style_matchups = style_matchups.dropna(subset=["winner_side"]).copy()

print("Rows after dropping unknown winner:", len(style_matchups))


# ------------------------------------------------------------
# 5. Randomly assign neutral fighter_1 / fighter_2 sides
# ------------------------------------------------------------

rng = np.random.default_rng(RANDOM_STATE)

# True = keep R as fighter_1, B as fighter_2
# False = swap B into fighter_1, R into fighter_2
style_matchups["keep_original_order"] = rng.choice(
    [True, False],
    size=len(style_matchups),
    replace=True
)

style_matchups["fighter_1"] = np.where(
    style_matchups["keep_original_order"],
    style_matchups["R_fighter"],
    style_matchups["B_fighter"]
)

style_matchups["fighter_2"] = np.where(
    style_matchups["keep_original_order"],
    style_matchups["B_fighter"],
    style_matchups["R_fighter"]
)

# Target: did fighter_1 win?
style_matchups["fighter_1_won"] = np.where(
    (
        (style_matchups["keep_original_order"] & (style_matchups["winner_side"] == "R")) |
        (~style_matchups["keep_original_order"] & (style_matchups["winner_side"] == "B"))
    ),
    1,
    0
)


# ------------------------------------------------------------
# 6. Add fighter_1 / fighter_2 style columns for every k
# ------------------------------------------------------------

for k in K_VALUES:
    r_col = f"R_style_k_{k}"
    b_col = f"B_style_k_{k}"

    f1_col = f"fighter_1_style_k_{k}"
    f2_col = f"fighter_2_style_k_{k}"

    style_matchups[f1_col] = np.where(
        style_matchups["keep_original_order"],
        style_matchups[r_col],
        style_matchups[b_col]
    )

    style_matchups[f2_col] = np.where(
        style_matchups["keep_original_order"],
        style_matchups[b_col],
        style_matchups[r_col]
    )

    # Keep style IDs categorical
    style_matchups[f1_col] = style_matchups[f1_col].astype(int).astype(str)
    style_matchups[f2_col] = style_matchups[f2_col].astype(int).astype(str)


# ------------------------------------------------------------
# 7. Final RF dataset
# ------------------------------------------------------------

final_cols = [
    "fighter_1",
    "fighter_2",
    "fighter_1_won"
]

for k in K_VALUES:
    final_cols.extend([
        f"fighter_1_style_k_{k}",
        f"fighter_2_style_k_{k}"
    ])

rf_data_final = style_matchups[final_cols].copy()

# Shuffle final rows
rf_data_final = (
    rf_data_final
    .sample(frac=1, random_state=RANDOM_STATE)
    .reset_index(drop=True)
)


print("\nTarget distribution:")
print(rf_data_final["fighter_1_won"].value_counts())

Rows before dropping missing styles: 8693
Rows after dropping missing styles: 7531

Rows before dropping unknown winner: 7531
Rows after dropping unknown winner: 7392

Target distribution:
fighter_1_won
1    3718
0    3674
Name: count, dtype: int64

# RF weighted

In [9]:
# ------------------------------------------------------------
# Run RF for each k
# ------------------------------------------------------------

CV = 15

rf_results = []

for k in K_VALUES:
    result_k = run_style_rf_for_k(
        rf_data_final=rf_data_final,
        k=k,
        random_state=RANDOM_STATE,
        test_size=0.20,
        cv=CV,
        print_results=True
    )

    rf_results.append(result_k)


# ------------------------------------------------------------
# Compare all k values
# ------------------------------------------------------------

rf_results_table = pd.DataFrame([
    {
        "k": r["k"],
        "rows_before_filter": r["rows_before_filter"],
        "rows_after_filter": r["rows_after_filter"],
        "same_style_rows_removed": r["same_style_rows_removed"],
        "target_1_rate": round(r["target_1_rate"], 3),
        "test_accuracy": round(r["test_accuracy"], 3),
        "test_balanced_accuracy": round(r["test_balanced_accuracy"], 3),
        "cv_mean_balanced_accuracy": round(r["cv_mean_balanced_accuracy"], 3),
        "cv_std_balanced_accuracy": round(r["cv_std_balanced_accuracy"], 3)
    }
    for r in rf_results
])

rf_results_table = (
    rf_results_table
    .sort_values("cv_mean_balanced_accuracy", ascending=False)
    .reset_index(drop=True)
)

print("\n" + "=" * 80)
print("Random Forest performance by k")
print("=" * 80)

display(rf_results_table)

best_k = rf_results_table.loc[0, "k"]
best_cv_score = rf_results_table.loc[0, "cv_mean_balanced_accuracy"]

print(f"\nBest k by CV balanced accuracy: {best_k}")
print(f"Best CV balanced accuracy: {best_cv_score}")

------------------------------------------------------------
k = 2
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 2779
Same-style rows removed: 4613

Target distribution:
fighter_1_won
1    0.512
0    0.488
Name: proportion, dtype: float64
fighter_1_won
1    1422
0    1357
Name: count, dtype: int64

Test accuracy: 0.541
Test balanced accuracy: 0.541

Confusion matrix:
[[153 132]
 [123 148]]

15-fold CV balanced accuracy:
[0.544 0.521 0.491 0.409 0.482 0.539 0.535 0.513 0.557 0.517 0.518 0.553
 0.464 0.531 0.482]
Mean: 0.51
Std: 0.038

------------------------------------------------------------
k = 3
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 3566
Same-style rows removed: 3826

Target distribution:
fighter_1_won
1    0.5
0    0.5
Name: proportion, dtype: float64
fighter_1_won
1    1784
0    1782
Name: count, dtype: int64

Test accuracy: 0.482
Test balanced accuracy: 0.482

Confusion matrix:
[[168 189]
 [181 176]]

15-fold CV balanced accuracy:
[0.487 0.458 0.508 0.5   0.487 0.479 0.517 0.559 0.483 0.445 0.513 0.443
 0.481 0.405 0.519]
Mean: 0.486
Std: 0.036

------------------------------------------------------------
k = 4
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 4227
Same-style rows removed: 3165

Target distribution:
fighter_1_won
0    0.501
1    0.499
Name: proportion, dtype: float64
fighter_1_won
0    2118
1    2109
Name: count, dtype: int64

Test accuracy: 0.593
Test balanced accuracy: 0.593

Confusion matrix:
[[243 179]
 [165 259]]

15-fold CV balanced accuracy:
[0.604 0.564 0.624 0.603 0.571 0.557 0.617 0.557 0.55  0.603 0.543 0.582
 0.548 0.566 0.573]
Mean: 0.577
Std: 0.026

------------------------------------------------------------
k = 5
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 4644
Same-style rows removed: 2748

Target distribution:
fighter_1_won
0    0.501
1    0.499
Name: proportion, dtype: float64
fighter_1_won
0    2326
1    2318
Name: count, dtype: int64

Test accuracy: 0.595
Test balanced accuracy: 0.595

Confusion matrix:
[[279 185]
 [191 274]]

15-fold CV balanced accuracy:
[0.613 0.577 0.642 0.565 0.629 0.539 0.665 0.565 0.59  0.582 0.573 0.524
 0.586 0.596 0.605]
Mean: 0.59
Std: 0.036

------------------------------------------------------------
k = 6
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 4859
Same-style rows removed: 2533

Target distribution:
fighter_1_won
1    0.503
0    0.497
Name: proportion, dtype: float64
fighter_1_won
1    2443
0    2416
Name: count, dtype: int64

Test accuracy: 0.579
Test balanced accuracy: 0.579

Confusion matrix:
[[291 198]
 [211 272]]

15-fold CV balanced accuracy:
[0.564 0.549 0.608 0.614 0.629 0.577 0.66  0.611 0.595 0.58  0.519 0.567
 0.583 0.605 0.56 ]
Mean: 0.588
Std: 0.034

------------------------------------------------------------
k = 7
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 5132
Same-style rows removed: 2260

Target distribution:
fighter_1_won
1    0.502
0    0.498
Name: proportion, dtype: float64
fighter_1_won
1    2577
0    2555
Name: count, dtype: int64

Test accuracy: 0.581
Test balanced accuracy: 0.581

Confusion matrix:
[[322 194]
 [236 275]]

15-fold CV balanced accuracy:
[0.58  0.554 0.605 0.623 0.626 0.559 0.629 0.62  0.591 0.591 0.529 0.538
 0.573 0.594 0.553]
Mean: 0.584
Std: 0.032

------------------------------------------------------------
k = 8
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 5740
Same-style rows removed: 1652

Target distribution:
fighter_1_won
1    0.505
0    0.495
Name: proportion, dtype: float64
fighter_1_won
1    2900
0    2840
Name: count, dtype: int64

Test accuracy: 0.585
Test balanced accuracy: 0.585

Confusion matrix:
[[341 239]
 [237 331]]

15-fold CV balanced accuracy:
[0.566 0.548 0.574 0.603 0.598 0.559 0.636 0.553 0.576 0.548 0.555 0.552
 0.555 0.599 0.568]
Mean: 0.573
Std: 0.025

------------------------------------------------------------
k = 9
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 5906
Same-style rows removed: 1486

Target distribution:
fighter_1_won
1    0.506
0    0.494
Name: proportion, dtype: float64
fighter_1_won
1    2986
0    2920
Name: count, dtype: int64

Test accuracy: 0.574
Test balanced accuracy: 0.574

Confusion matrix:
[[344 254]
 [249 335]]

15-fold CV balanced accuracy:
[0.578 0.552 0.571 0.606 0.563 0.606 0.613 0.522 0.56  0.591 0.57  0.571
 0.541 0.566 0.546]
Mean: 0.57
Std: 0.025

------------------------------------------------------------
k = 10
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 6063
Same-style rows removed: 1329

Target distribution:
fighter_1_won
1    0.508
0    0.492
Name: proportion, dtype: float64
fighter_1_won
1    3082
0    2981
Name: count, dtype: int64

Test accuracy: 0.583
Test balanced accuracy: 0.583

Confusion matrix:
[[350 267]
 [239 357]]

15-fold CV balanced accuracy:
[0.556 0.587 0.583 0.626 0.6   0.58  0.586 0.547 0.554 0.555 0.528 0.552
 0.594 0.546 0.567]
Mean: 0.571
Std: 0.025

------------------------------------------------------------
k = 11
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 6229
Same-style rows removed: 1163

Target distribution:
fighter_1_won
1    0.508
0    0.492
Name: proportion, dtype: float64
fighter_1_won
1    3164
0    3065
Name: count, dtype: int64

Test accuracy: 0.566
Test balanced accuracy: 0.565

Confusion matrix:
[[403 230]
 [311 302]]

15-fold CV balanced accuracy:
[0.55  0.577 0.581 0.605 0.593 0.586 0.589 0.562 0.542 0.596 0.569 0.554
 0.559 0.557 0.537]
Mean: 0.57
Std: 0.02

------------------------------------------------------------
k = 12
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 6280
Same-style rows removed: 1112

Target distribution:
fighter_1_won
1    0.507
0    0.493
Name: proportion, dtype: float64
fighter_1_won
1    3182
0    3098
Name: count, dtype: int64

Test accuracy: 0.572
Test balanced accuracy: 0.572

Confusion matrix:
[[346 290]
 [248 372]]

15-fold CV balanced accuracy:
[0.565 0.593 0.577 0.651 0.615 0.59  0.63  0.586 0.548 0.575 0.55  0.568
 0.565 0.573 0.566]
Mean: 0.583
Std: 0.028

------------------------------------------------------------
k = 13
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 6327
Same-style rows removed: 1065

Target distribution:
fighter_1_won
1    0.502
0    0.498
Name: proportion, dtype: float64
fighter_1_won
1    3178
0    3149
Name: count, dtype: int64

Test accuracy: 0.604
Test balanced accuracy: 0.604

Confusion matrix:
[[405 231]
 [270 360]]

15-fold CV balanced accuracy:
[0.602 0.592 0.578 0.64  0.628 0.607 0.604 0.581 0.564 0.562 0.543 0.583
 0.584 0.594 0.606]
Mean: 0.591
Std: 0.024

------------------------------------------------------------
k = 14
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 6401
Same-style rows removed: 991

Target distribution:
fighter_1_won
1    0.501
0    0.499
Name: proportion, dtype: float64
fighter_1_won
1    3209
0    3192
Name: count, dtype: int64

Test accuracy: 0.562
Test balanced accuracy: 0.562

Confusion matrix:
[[360 282]
 [279 360]]

15-fold CV balanced accuracy:
[0.581 0.581 0.576 0.63  0.602 0.583 0.602 0.59  0.553 0.56  0.539 0.556
 0.587 0.589 0.582]
Mean: 0.581
Std: 0.022

------------------------------------------------------------
k = 15
------------------------------------------------------------
Rows before same-style filter: 7392
Rows after same-style filter: 6391
Same-style rows removed: 1001

Target distribution:
fighter_1_won
1    0.501
0    0.499
Name: proportion, dtype: float64
fighter_1_won
1    3201
0    3190
Name: count, dtype: int64

Test accuracy: 0.573
Test balanced accuracy: 0.573

Confusion matrix:
[[396 245]
 [301 337]]

15-fold CV balanced accuracy:
[0.569 0.566 0.587 0.613 0.594 0.594 0.599 0.57  0.561 0.552 0.566 0.544
 0.556 0.591 0.585]
Mean: 0.576
Std: 0.019

================================================================================
Random Forest performance by k
================================================================================

,k,rows_before_filter,rows_after_filter,same_style_rows_removed,target_1_rate,test_accuracy,test_balanced_accuracy,cv_mean_balanced_accuracy,cv_std_balanced_accuracy
0,13,7392,6327,1065,0.502,0.604,0.604,0.591,0.024
1,5,7392,4644,2748,0.499,0.595,0.595,0.590,0.036
2,6,7392,4859,2533,0.503,0.579,0.579,0.588,0.034
3,7,7392,5132,2260,0.502,0.581,0.581,0.584,0.032
4,12,7392,6280,1112,0.507,0.572,0.572,0.583,0.028
5,14,7392,6401,991,0.501,0.562,0.562,0.581,0.022
6,4,7392,4227,3165,0.499,0.593,0.593,0.577,0.026
7,15,7392,6391,1001,0.501,0.573,0.573,0.576,0.019
8,8,7392,5740,1652,0.505,0.585,0.585,0.573,0.025
9,10,7392,6063,1329,0.508,0.583,0.583,0.571,0.025
10,11,7392,6229,1163,0.508,0.566,0.565,0.570,0.020
11,9,7392,5906,1486,0.506,0.574,0.574,0.570,0.025
12,2,7392,2779,4613,0.512,0.541,0.541,0.510,0.038
13,3,7392,3566,3826,0.500,0.482,0.482,0.486,0.036

Best k by CV balanced accuracy: 13
Best CV balanced accuracy: 0.591